version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./ai_events.db
      - ASYNC_DATABASE_URL=sqlite+aiosqlite:///./ai_events.db
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      - redis
    networks:
      - ai-events-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - ai-events-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-events-network

volumes:
  backend_data:
  redis_data:

networks:
  ai-events-network:
    driver: bridge